const num = 5645689003214;
console.log(`Here num is ${num} and its type is ${typeof(num)}`);
const numObject = new Number(5);
console.log(`Here numObject is ${numObject} and its type is ${typeof(numObject)}`);
let stringOfNum = num.toString();
console.log(`Here string version of num is ${stringOfNum} as its type is ${typeof(stringOfNum)}`);
let lengthOfNumber = num.toString().length;
console.log(`Here length of number is ${lengthOfNumber}`);
let num1 = 5.642425365365;
let specifyNoOfDecimalPoints = num1.toFixed(4);
console.log(`num1 with 4 decimal points is ${specifyNoOfDecimalPoints}`);
let totalNumbersPrecision = num1.toPrecision(4);
//!toPrecision counts number as a whole while toFixed only count decimal points
console.log(`num1 with 4 precision places is ${totalNumbersPrecision}`);
let numberExponential = num1.toExponential(2);
console.log(numberExponential);
let localeString = num1.toLocaleString('en-US');
console.log(localeString);
let maxPossibleValue = Number.MAX_VALUE;
let minPossibleValue = Number.MIN_VALUE;
console.log(`Max Possible Value is ${maxPossibleValue} and Min Possible Value is ${minPossibleValue}`);