console.log(100);
console.log('Hello World');
console.log(20,'Hello',true);
let x = 100;
console.log(x);
console.error('Error');
console.warn('warning');
console.table({name:'Divyanshu',email:'divyanshujain121@gmail.com'});
console.group('simple');
console.log(x);
console.error('Error');
console.warn('Warning');
console.groupEnd();
const styles = 'padding:10px;background-color:white;color:green';
console.log('%c Styles are applied ',styles);